b3_forum/urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum'),
]

tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import b2_profil.urls as profil
import b1_utama.urls as login
import b3_forum.urls as forum
import b4_tanggapan.urls as tanggapan

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=True), name='r-login'),
    url(r'^login/', include(login, namespace='login')),
	url(r'^forum/', include(forum, namespace='forum')),
    url(r'^profil/', include(profil, namespace='profil')),
    url(r'^tanggapan/', include(tanggapan, namespace='tanggapan'))
]

b3_forum/models.py
from django.db import models

class Forum(models.Model):
    #perusahaan = models.ForeignKey(Perusahaan)
    lowongan = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

b3_forum/forms.py
from django import forms

class Forum_Lowongan(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    lowongan_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Masukan deskripsi Forum'
    }

    lowongan = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=lowongan_attrs))

b3_forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Forum_Lowongan
from .models import Forum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
response = {}
def index(request):
    forum = Forum.objects.all().order_by('-created_date')
    
    #pagination
    paginator = Paginator(forum, 5)
    page = request.GET.get('page')
    try:
        halaman = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        halaman = paginator.page(1)


    response['Forum'] = halaman
    html = 'b3_forum/b3_forum.html'
    response['Forum_Lowongan'] = Forum_Lowongan
    return render(request, html, response)

def add_forum(request):
    form = Forum_Lowongan(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['lowongan'] = request.POST['lowongan']
        forum = Forum(lowongan=response['lowongan'])
        forum.save()
        return HttpResponseRedirect('/forum/')
    else:
        return HttpResponseRedirect('/forum/')

b3_forum/templates/b3_forum/b3_forum.html
{% extends "layout/base.html" %} 
{% load staticfiles%} 

{% block style %}
<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/b3_forum.css' %}">
{% endblock %}


{% block content %}
<style>
       
        .profile-img {
        background-image: url('http://mulyafotocopy.com/wp-content/uploads/2013/11/gedung-pt.mmc_.png');
        background-size:cover;
        background-position: center;
        background-repeat:no-repeat;
        margin: auto;
        }
		
		.status_box{
            margin-left: 0px;
            width: auto;
            margin-right: 15px;
        }
      
</style>

<section>
    <h3 class="forum-list-title" align="center"> Forum Lowongan Kerja </h3>
	<br>
	<br>
    <div class="container">
            {% if Forum %}
                {% for forum in Forum %}
				<div class="status_box">
					<br><br><br>
					<div class="profile-img img-circle" style="width: 70px ; height: 70px;display:inline-block ; vertical-align: middle; "></div>
                
				<div style="display: inline-block;  margin-top: 15px; margin-bottom: auto; vertical-align: middle"">
					<p style="margin-left: 20px"> {{ forum.created_date}} </p>  
					<p style="font-size: 20px;margin-left: 20px">{{ forum.lowongan }}</p>
				</div>
				
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Maaf!</strong> Tidak ada forum
            </div>
            {% endif %}
        </div>


<div align="center">
    <span class="step-links">
		<br><br><br><br>
        {% if Forum.has_previous %}
            <a href="?page={{ Forum.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ Forum.number }} of {{ Forum.paginator.num_pages }}.
        </span>

        {% if Forum.has_next %}
            <a href="?page={{ Forum.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
<br>
<br>
<br>
</section>

    <div id="myDiv">
    <input id="new_forum" class="btn btn-lg btn-block btn-primary" value="Tambah Forum Lowongan" onclick="show()"> 
    </div>

    <div id="form" style="display:none" class="container">
      <form id="form" method="POST" action="{% url 'forum:add_forum' %}">
          <h3 align="center">Tambah Forum Lowongan Kerja</h3>
		  <br>
          {% csrf_token %}
          {{ Forum_Lowongan }}
		  <br>
		  <br>
          <input id="submit" type="submit" class="btn btn-lg btn-block btn-primary" value="Submit" onclick="add()">
          <br>
      </form>
    </div>
	<br>
	<br>
	<br>
	<br>
    
    
    {% block javascript%}
    <script>
    function show(){

        var x = document.getElementById("form");
        
        if(x.style.display === "none"){
        x.style.display = "block";
        }else{
          x.style.display = "none";
        }
        $('#new_forum').hide();

        }

    function add(){
        var x = document.getElementById("form");
        
        if(x.style.display === "none"){
        x.style.display = "block";
        }else{
          x.style.display = "none";
        }
        $('#new_forum').show();
    }

    </script>
    {% endblock %}
    {% endblock %}
    