b1_utama/urls.py
from django.conf.urls import url
from .views import index
from b2_profil.views import add_company
from b2_profil.views import index as profil_page

urlpatterns = [
    url(r'^$', index, name='index'),
    # url(r'^(?P<id>\d+)/$', profil_page, name='index'),
    url(r'^add_company/$',add_company,name='add_company')
]

tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import b2_profil.urls as profil
import b1_utama.urls as login
import b3_forum.urls as forum
import b4_tanggapan.urls as tanggapan

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=True), name='r-login'),
    url(r'^login/', include(login, namespace='login')),
	url(r'^forum/', include(forum, namespace='forum')),
    url(r'^profil/', include(profil, namespace='profil')),
    url(r'^tanggapan/', include(tanggapan, namespace='tanggapan'))
]

templates/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<div class="footer">
<p> All rights reserved to Lala 2016</p>
</div>

templates/partials/header.html
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Recruit.me</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'login:index' %}">Home</a></li>
      <li class="active"><a href="{% url 'login:index' %}">Profile</a></li>
      <li class="active"><a href="{% url 'forum:index' %}#forum">Forum</a></li>
      </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><a href="javascript:void(0);" onclick="logout()">Logout</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    </ul>
  </div>