b4_tanggapan/urls.py
from django.conf.urls import url
from .views import add_reply, submit_reply

urlpatterns = [
    url(r'^add-reply/(?P<id>\d)', add_reply, name='add-reply'),
    url(r'^tanggapan/(?P<id>\d)', submit_reply, name='submit-reply')
]

tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import b2_profil.urls as profil
import b1_utama.urls as login
import b3_forum.urls as forum
import b4_tanggapan.urls as tanggapan

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=True), name='r-login'),
    url(r'^login/', include(login, namespace='login')),
	url(r'^forum/', include(forum, namespace='forum')),
    url(r'^profil/', include(profil, namespace='profil')),
    url(r'^tanggapan/', include(tanggapan, namespace='tanggapan'))
]

b4_tanggapan/models.py
from django.db import models
from b3_forum.models import Forum as forum

class Reply(models.Model):
    sender = models.CharField(max_length=60,default="Unknown Applicant")
    message = models.CharField(max_length=250)
    created_date = models.DateTimeField(auto_now_add=True)
    forum = models.ForeignKey(forum)

b4_tanggapan/forms.py
from django import forms


class ReplyForm(forms.Form):
    sender = forms.CharField(max_length=60)
    message = forms.CharField(max_length=250)

b4_tanggapan/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from b3_forum.models import Forum
from .models import Reply
from .forms import ReplyForm
# Create your views here.

def add_reply(request,id):
    response = {'replyform': ReplyForm, 'id':id}
    html = 'tanggapan_form_page.html'
    return render(request,html,response)

def submit_reply(request, id):
    forum = Forum.objects.get(id=id)
    reply = ReplyForm(request.POST)
    if(reply.is_valid()):
        sender = reply.cleaned_data["sender"]
        message = reply.cleaned_data["message"]
        print(sender,message)
        Reply.objects.create(sender=sender,message=message, forum=forum)
        if(reply.is_valid()):
            return redirect('/login/')
        else:
            response = {'id': id}
            html = 'tanggapan_form_page.html'
            return render(request,html,response)
    else:
        add_reply(request,id)

def paginate(request, forum_list):
    # Paginator
    paginator = Paginator(forum_list, 3)

    try:
        forum = paginator.page(request)
    except PageNotAnInteger:
        forum = paginator.page(1)
    except EmptyPage:
        forum = paginator.page(paginator.num_pages)

    index = forum.number - 1

    max_index = len(paginator.page_range)

    start_index = index if index >= 10 else 0
    end_index = 10 if index < max_index - 10 else max_index

    page_range = list(paginator.page_range)[start_index:end_index]

    data_paginate = {'forum': forum, 'page_range': page_range}
    return data_paginate

b4_tanggapan/templates/tanggapan_form_page.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/b1_utama.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-7">
                <h1 style=" margin-top: 10px; font-weight: 550"> Add Reply </h1>
                <form action="{% url 'tanggapan:submit-reply' id %}" method="POST">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-block">
                            <!-- Form for new name -->
                            <h5 class="card-title" > Name </h5>
                                <input type="text" class="form-control" name="sender" id="sender" />
                            <h5 class="card-title" style=" margin-top: 10px"> Reply </h5>
                                <input type="text" class="form-control" name="message" id="message" />
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary float-right" style="margin-top: 8px; margin-bottom: 20px" id="button">Add Reply</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}