b1_utama/urls.py
from django.conf.urls import url
from .views import index
from b2_profil.views import add_company
from b2_profil.views import index as profil_page

urlpatterns = [
    url(r'^$', index, name='index'),
    # url(r'^(?P<id>\d+)/$', profil_page, name='index'),
    url(r'^add_company/$',add_company,name='add_company')
]

b4_tanggapan/urls.py
from django.conf.urls import url
from .views import add_reply, submit_reply

urlpatterns = [
    url(r'^add-reply/(?P<id>\d)', add_reply, name='add-reply'),
    url(r'^tanggapan/(?P<id>\d)', submit_reply, name='submit-reply')
]

tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import b2_profil.urls as profil
import b1_utama.urls as login
import b3_forum.urls as forum
import b4_tanggapan.urls as tanggapan

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=True), name='r-login'),
    url(r'^login/', include(login, namespace='login')),
	url(r'^forum/', include(forum, namespace='forum')),
    url(r'^profil/', include(profil, namespace='profil')),
    url(r'^tanggapan/', include(tanggapan, namespace='tanggapan'))
]

b1_utama/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    id = models.CharField('id', max_length=20, primary_key=True, )
    name = models.CharField('Name', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

b4_tanggapan/models.py
from django.db import models
from b3_forum.models import Forum as forum

class Reply(models.Model):
    sender = models.CharField(max_length=60,default="Unknown Applicant")
    message = models.CharField(max_length=250)
    created_date = models.DateTimeField(auto_now_add=True)
    forum = models.ForeignKey(forum)

b1_utama/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .models import User
from b3_forum.models import Forum
from b4_tanggapan.views import paginate


# Create your views here.
response={}
def index(request):
    html = 'b1_utama/b1_utama.html'
    forum_list = Forum.objects.all()

    page = request.GET.get('page', 1)
    # membuat paginasi
    paginate_data = paginate(page, forum_list)
    forum = paginate_data['forum']
    page_range = paginate_data['page_range']

    response = {'author':'Nixi Sendya',"forum_list": forum, "page_range": page_range}

    return render(request,html,response)

b1_utama/templates/b1_utama/b1_utama.html
{% extends "layout/base.html" %}

{% load staticfiles %}
{% load static %}

{% block script %}
<!-- Script -->
<script type="text/javascript" src="//platform.linkedin.com/in.js">
api_key:   81kze45gb69r8f
onLoad:    onLinkedInLoad
authorize: true
</script>
<script src="{% static 'js/b1_utama.js' %}"></script>
{% endblock %}


{% block content %}
<body>
<section id="showcase">
	<div class="container">
	<h1> JOIN US</h1>
	<p> Apply your skills to help others </p>
	<section id="linkedInbutton">
	{% csrf_token %}
	<script type="in/Login"></script>
	</div>
</section>

<section id="jobvacancy">
	<div class="jobtitle">
	<h1> Latest Job Listings</h1>
	</div>
</section>

<!-- display profile info -->
<div id="profileData" >
<div class="container">
    <div class="row">
        <div class='col'>
            </div>
            <p><a href="javascript:void(0);" onclick="logout()">Logout</a></p>
            <div id="picture"></div>
            <div class="info">
                <p id="name"></p>
                <p id="intro"></p>
                <p id="email"></p>
                <p id="location"></p>
                <p id="link"></p>
            </div>
        </div>
        <div class="col">
            <ul class="list-group" id='company-list'>
            
            </ul>
        </div>
    </div>
    
</div>
</div>

<div id="companyData" style="display: none;">
<div class="container">
    <div id="companyLogo"></div>
    <div class="info">
        <p id="companyName"></p>
        <p id="description"></p>
        <p id="ticker"></p>
        <p id="companyWeb"></p>
    </div>
</div>
</div>
</body>
<br><br>
<div class="py-5 bg-light text-dark">
    <div class="container">
      <div class="row">
          {% if forum_list %}
              {% for i in forum_list %}
                <div class="col-md-4 my-3">
                  <div class="card">
                    <img class="img-fluid imgtofit" style="background-image: url('http://www.huntsland-nutrition.com/wp-content/uploads/2015/05/company.jpg');">
                    <div class="card-body">
                    <h5 style="text-align: center"><b>Nama Perusahaan</b></h5>
                      <p>{{ i.lowongan }}</p>
                        <p>{{ i.created_date }}</p>
                      <br>
                    </div>
                      <form class="class=form-horizontal " role="form" action="{% url "tanggapan:add-reply" i.id %}" method="get" >
                        <button class="tanggapan-btn btn-success">Reply</button>
                      </form>

                    <div class="tanggapan-container">
                    {% for j in i.reply_set.all %}
                        <div class="tanggapan">
                            <h5 class="reply-message"><em>"{{ j.message }}"</em></h5>
                            <h5 class="reply-info"><strong>{{ j.sender }} on {{ j.created_date }}</strong></h5>
                        </div>
                    {% endfor %}
                    </div>
                  </div>
                </div>
              {% endfor %}
          {% endif %}
      </div>
        {% if forum_list.has_other_pages %}
            <ul class="pagination">
                {% if forum_list.has_previous %}
                    <li><a href="{% url 'login:index' %}">&laquo;</a></li>
                    <li><a href="?page={{ forum_list.previous_page_number }}">&lsaquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&lsaquo;</span></li>
                {% endif %}
                {% for page in page_range %}
                    {% if forum_list.number == page %}
                        <li class="active"><span>{{ page }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if forum_list.has_next %}
                    <li><a href="?page={{ forum_list.next_page_number }}">&rsaquo;</a></li>
                    <li><a href="?page={{ forum_list.paginator.num_pages }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&rsaquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
  </div>
<br><br>

<div class="py-5 bg-dark text-white" style="background-color: #f4f4f4">
    <div class="container">
      <div class="row">
        <div class="col-md-12 mt-3 text-center">
          <p>© Copyright 2017 Kelompok C12 - All rights reserved.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 


<!-- <br><br>
<center><button>Login</button></center><br><br> -->